### ISSUE TITLE
Is it possible to validate all inputs on submit?

### ISSUE THREAD

**Issue by rockingskier** [christianalfoni/formsy-react#170]
When the form is submitted is it possible to trigger validation on all inputs in the form?

Currently `onInvalid` fires on the form however it does not trigger all validation messages to appear.

**Comment by christianalfoni** [comment]
I believe this is the same as #147 ?

It depends on the user experience here. Normally you would not allow a submit when any of the elements are invalid. So in the component with your Formsy form you use `onValid` and `onInvalid` to track when the submit button actually can be pressed.

But the issue mentioned here is about allowing validations to run only when submitting, not as you change the value of the inputs. Would that work for you?

**Comment by rockingskier** [comment]
#147 is definitely headed in the right direction.

I guess what I am looking for isn't validation on submit necessarily but more for "You missed a field" to highlight required fields.

With larger forms the user might miss a field and we don't want to ask them to review the whole form to find it before we enable the submit button.  Personally, allowing them to submit and then highlight missed fields is a better user experience.

**Comment by jaraquistain** [comment]
@rockingskier My solution for that kind of experience in the past has been to have an error message associated with each input that is populated by either "required" or its error message. You can style this whole error state however you'd like, but the important thing is that none of the styles are visible unless there is a "show-errors" class on the form itself (controlled either manually or tied to some state value).

That way you can `setState({ showErrors: true })` inside of your `onInvalidSubmit` handler.

The net result is that the user will only see validation errors when they try to submit the form with invalid values, including whatever messaging you had styled for required fields. This may or may not be your desired experience as its very subjective, but in my opinion the most common use case is correct form filling so its best to not disrupt the user with immediate validation.

***Validated Form Component***
```jsx
import React from "react";
import Formsy from "formsy-react";

let ValidatedInput = React.createClass({
    mixins: [Formsy.Mixin],
    propTypes: {
        name: React.PropTypes.string.isRequired,
        type: React.PropTypes.string,
        inputClassName: React.PropTypes.string,
        placeholder: React.PropTypes.string,
        label: React.PropTypes.string
    },
    changeValue(e) {
        this.setValue(e.currentTarget.value);
        this.props.onChange(e);
    },
    render() {
        let errorMessage = this.getErrorMessage();

        return (
            <div
                className={["eo-validated-input", this.props.className, (this.showError() ? "error" : null), (this.showRequired() ? "required" : null)].join(" ")}>
                { this.props.label ?
                    <label className="eo-input-label" htmlFor={this.props.name}>{this.props.label}</label> : null }
                <input placeholder={this.props.placeholder}
                       className={["eo-input", this.props.inputClassName].join(" ")}
                       type={this.props.type || "text"}
                       name={this.props.name}
                       onChange={this.changeValue}
                       value={this.getValue()}/>
                <span className="eo-validation-error">{this.showRequired() ? "Required" : errorMessage}</span>
            </div>
        );
    }
});

export default ValidatedInput;
```
***Relevant error styles***
```css
.show-errors {
     .error, .required {
         .eo-input {
             border: 1px solid $eo-red;
             color: $eo-red;
             @include placeholder {
                 color: $eo-red;
             }
         }
         .eo-validation-error {
             display: block;
             color: $eo-red;
             @include font-smoothing();
         }
     }
     .eo-form-validation-error {
         color: $eo-red;
         margin: $eo-gutter/4 0;
     }
 }
```
